BUILDROOT ?= ..

CSRCS = \
	./string/strchr/strchr.c \
	string/strlen/strlen.c \
	string/strcpy/strcpy.c \
	string/memset/memset.c \
	string/strcat/strcat.c \
	string/strcmp/strcmp.c \
	string/memcpy/memcpy.c \
	string/memmove/memmove.c \
	string/eat_front_whitespace/eat_front_whitespace.c \
	string/validate_char/validate_char.c \
	stdio/printck/printck.c \
	stdlib/itoa/itoa.c \
	stdlib/atoi/atoi.c \
	stdlib/strtoi/strtoi.c \
	stdio/sprintk/sprintk.c \
	stdio/printk/printk.c \
	stdio/scank/scank.c \
	unistd/sleep/sleep.c \
	unistd/get_opt/get_opt_count.c \
	unistd/get_opt/get_opt.c \
	stdlib/panik/panik.c \
	math/powk/powk.c \
	math/sqrtk/sqrtk.c \
	ctype/toupper/toupper.c\
	ctype/isdigit/isdigit.c

LIBNAME := c

include $(BUILDROOT)/library.mk
