BUILDROOT ?= ..

CSRCS = \
	./string/strchr/strchr.c \
	string/strlen/strlen.c \
	string/strcpy/strcpy.c \
	string/memset/memset.c \
	string/strcat/strcat.c \
	stdio/printck/printck.c \
	stdio/itoa/itoa.c \
	stdio/sprintk/sprintk.c \
	stdio/printk/printk.c \
	stdio/scank/scank.c \
	unistd/sleep/sleep.c \
	stdlib/panik/panik.c \
	math/powk/powk.c \
	math/sqrtk/sqrtk.c \
	ctype/toupper/toupper.c

LIBNAME := c

include $(BUILDROOT)/library.mk

#all:
#	cd stdio;make
#	cd stdlib;make
#	cd string;make
#	cd math;make
#	cd unistd;make
