language: c
script: CC=gcc-5 make

# safelist
branches:
  only:
  - travisci

env:
  - CC=gcc-5

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5
    - nasm
    - grub-common
    - xorriso
