site_name: BoneOS
site_url: https://boneos.org
repo_url: https://github.com/Bone-Project/BoneOS
repo_name: BoneOS
site_description: BoneOS is an Operating System designed to be simple and at the same time powerful.
site_favicon: BoneOS.png

pages:
 - Home: 'index.md'
 - Installation:
      - 'Installation': 'Installation/Installation.md'
      - 'Running the iso file': 'Installation/NormalInstall.md'
      - 'Building from source': 'Installation/SourceInstall.md'
      - 'Troubleshooting': 'Issues/Troubleshooting.md'
 - Virtual Machines:
      - 'Virtual Machines': 'Virtual-Machines/VirtualMachine.md'
      - 'Using QEmu': 'Virtual-Machines/QEmu.md'
      - 'Using Virtual Box': 'Virtual-Machines/VirtualBox.md'
 - Configuration:
      - 'Configuration': 'Configuration/Configuration.md'
      - 'Changing the Assembler': 'Configuration/ChangeAssembler.md'
      - 'Changing the Architecture': 'Configuration/ChangeArchitecture.md'
      - 'Changing the Compiler': 'Configuration/ChangeCompiler.md'
      - 'Changing the Linker': 'Configuration/ChangeLinker.md'
      - 'Changing the Platform': 'Configuration/ChangePlatform.md'
 - Utilities:
      - 'Utilities provided': 'Utilities/AdditionalUtilities.md'
      - 'Using Nodemon': 'Utilities/Nodemon.md'
 - Shell:
      - 'Shell': 'Shell/Shell.md'
      - 'Shortcuts': 'Shell/ShortcutKeys.md'
 - Commands:
      - 'Commands': 'Commands/Commands.md'
      - 'clear': 'Commands/clear.md'
      - 'poweroff': 'Commands/poweroff.md'
      - 'reboot': 'Commands/reboot.md'
      - 'boneshell': 'Commands/boneshell.md'
      - 'exit': 'Commands/exit.md'
      - 'beep': 'Commands/beep.md'
      - 'date': 'Commands/date.md'
      - 'logname': 'Commands/logname.md'
      - 'whoami': 'Commands/whoami.md'
      - 'cursor': 'Commands/cursor.md'
      - 'pwd': 'Commands/pwd.md'
      - 'watch': 'Commands/watch.pwd'
