pages:
 - Home: 'index.md'
 - Installation:
	- 'Installation': 'Installation/Installation.md'
	- 'Running the iso file': 'Installation/NormalInstall.md'
	- 'Building from source': 'Installation/SourceInstall.md'
	- 'Troubleshooting': 'Issues/Troubleshooting.md'
 - Virtual Machines:
	- 'Virtual Machines': 'Virtual-Machines/VirtualMachine.md'
	- 'Using QEmu': 'Virtual-Machines/QEmu.md'
	- 'Using Virtual Box': 'Virtual-Machines/VirtualBox.md'
 - Configuration:
	- 'Configuration': 'Configuration/Configuration.md'
	- 'Changing the Assembler': 'Configuration/ChangeAssembler.md'
	- 'Changing the Architecture': 'Configuration/ChangeArchitecture.md'
	- 'Changing the Compiler': 'Configuration/ChangeCompiler.md'
	- 'Changing the Linker': 'Configuration/ChangeLinker.md'
	- 'Changing the Platform': 'Configuration/ChangePlatform.md'

 - Utilities:
	- 'Utilities provided': 'AdditionalUtilities.md'
	- 'Using Nodemon': 'Nodemon.md'

