#ifndef _DRV_VIDEO_VGA_TEXTMODE_CURSOR_H_
#define _DRV_VIDEO_VGA_TEXTMODE_CURSOR_H_

#define CURSOR_REGISTER_SELECT 0x3D4
#define CURSOR_DATA_SEND 0x3D5

#define CRTC_PORT 0x3D4

#define CRSR_START_UNDERLINE 15
#define CRSR_END_UNDERLINE 15

#define CRSR_START_BLOCK 0
#define CRSR_END_BLOCK 20

#endif /*_DRV_VIDEO_VGA_TEXTMODE_CURSOR_H_*/

