#ifndef _DRV_VIDEO_VGA_TEXTMODE_CURSOR_H_
#define _DRV_VIDEO_VGA_TEXTMODE_CURSOR_H_

#define CURSOR_REGISTER_SELECT 0x3D4
#define CURSOR_DATA_SEND 0x3D5

#define CRTC_PORT 0x3D4

#define CRSR_START_DEFAULT 15
#define CRSR_END_DEFAULT 15

#endif /*_DRV_VIDEO_VGA_TEXTMODE_CURSOR_H_*/

