#ifndef  _MISC_STATUSCODES_H_
#define  _MISC_STATUSCODES_H_

#define STATUS_OK 0
#define STATUS_FAIL 1
#define STATUS_VERSION_NA 0x2F
#define STATUS_VALID 0x1

#define STATUS_DRIVER_OK 0x0
#define STATUS_DRIVER_MALFUNCTION 0x1

#endif /*_MISC_STATUSCODES_H_*/






